### ISSUE TITLE
Question: Is there a way to do remote $ref?

### ISSUE THREAD

**Issue by owaaa** [gangverk/flask-swagger#22]
Will $ref work to a remote server. When i was attempting it seemed to insert '/' before the url but I was wondering if I am missing something else?

**Comment by atlithorn** [comment]
If it works in swagger-ui (according to [this](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#reference-object) it seems it would) it will work with flask-swagger. Haven't done this myself so I can't vouch for it. 

Feel free to re-open this issue if you find that there is a shortcoming in flask-swagger that prevents you from doing this
