### ISSUE TITLE
Doc example showing root level definitions?

### ISSUE THREAD

**Issue by mikesiegel** [gangverk/flask-swagger#31]
Would it be possible to provide documentation as how one would use root-level definitions?  In the current examples the definitions are implemented per path or operation object.

I'd like to keep my definitions similar to the Petstore example, at the root level of the spec so they can be referenced by multiple paths/operation objects.  Is that possible with flask-swagger?

Thanks!

**Comment by atlithorn** [comment]
Yes you can simply follow the swagger spec eg.

```
type: array
items:
   $ref: "#/definitions/Event"
```

Where `Event` is a definition that was defined elsewhere (any other response/parameter via `schema`)
