### ISSUE TITLE
Pip source code is different from github master branch

### ISSUE THREAD

**Issue by jhonjairoroa87** [gangverk/flask-swagger#36]
Hi, I installed flask-swagger using 'pip install flask-swagger' and I noticed the downloaded source code is different from the one published in the master branch. Notice "_parse_docstring" function on the left and "_find_from_file" on the right.

<img width="1437" alt="screenshot 2016-09-30 14 38 50" src="https://cloud.githubusercontent.com/assets/619203/19004480/a8d37272-871b-11e6-84ae-a2d90a277a9b.png">

Maybe I'm doing something wrong and I haven't realize it, any thoughts?

**Comment by atlithorn** [comment]
You're not doing anything wrong - I simply haven't released the new version.

Apologies - it's there now.

**Comment by jhonjairoroa87** [comment]
Thanks a lot @atlithorn !!
