### ISSUE TITLE
Multiple path parameters and multiple endpoints

### ISSUE THREAD

**Issue by hnb2** [gangverk/flask-swagger#37]
Hi there,

I currently have a flask_restful Resource with 2 path parameters: one compulsory, and one optional. I followed [this recommendations](http://stackoverflow.com/a/26379214/6487514) of writing it this way:

`api.add_resource(ProductsResource, '/products/<string:slug>', '/products/<string:slug>/<string:color>')`

```
class ProductsResource(Resource):
      @marshal_with(products_fields)
      def get(self, slug, color=None):
           ....
```

Then, i have the following YML documentation in the docstring regarding parameters:

```
...
- name: slug
   in: path
   description: product's slug
   type: string
   required: true
- name: color
   in: path
   description: product's color
   type: string
   required: true
```

When I go to my project on http://localhost:5000/spec, I see that I have 2 endpoint generated:
- http://localhost:5000/products/{slug}
- http://localhost:5000/products/{slug}/{color}

But, for both endpoints there are those 2 required parameters, resulting in a swagger error: `Path parameter is defined but is not declared: color`. 

Do you think it would be possible to filter the path parameters based on the endpoints used ? Here it would mean filter out 'color' for the first endpoint.

Thanks,
Pierre.

**Comment by hnb2** [comment]
I'm also open to alternative solutions in order to avoid this problem, in case it is possible to do it without changing `flask-swagger`'s code. Like, changing the Resource's structure by creating 2 functions instead of one, or anything.

**Comment by atlithorn** [comment]
I'm not saying it's optimal but yes you could create "wrapper" methods for resources. The wrappers have separate YAML but call a shared method internally.

It's not obvious to me how to do this via flask_swagger without refactoring the YAML format.

**Comment by hnb2** [comment]
Alright, i'll see what I can do using wrapper methods, thanks for your help.
