### ISSUE TITLE
Invalid path parameter

### ISSUE THREAD

**Issue by cloudguruab** [gangverk/flask-swagger#66]
- The following path is listed in docs as: https://api.getsling.com/#/timeclock/post_timeclock_clockin
- This path is for clocking in for shifts, but it is wrong. 
- The valid path for proper documentation changes by the following: 
```
Old Path: /timeclock/clockin
New path: /{org_id}/timeclock/clockin
```

**Comment by mrname** [comment]
> * The following path is listed in docs as: https://api.getsling.com/#/timeclock/post_timeclock_clockin
> * This path is for clocking in for shifts, but it is wrong.
> * The valid path for proper documentation changes by the following:
> 
> ```
> Old Path: /timeclock/clockin
> New path: /{org_id}/timeclock/clockin
> ```

Hey @cloudguruab this repository is just the library that Sling (and others) use to auto-generate documentation from their code, whereas your issue is related directly to Sling documentation. Would you mind closing this and opening an issue over here? https://github.com/getsling/getsling-api-docs

**Comment by cloudguruab** [comment]
@mrname Sure thing!
